'use client'
import React, { useMemo, useState } from 'react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'

interface ProgramStudi {
    no: number
    jenis: 'Tinggi' | 'Menengah'
    satdik: string
    [key: string]: string | number
}


interface DataByTriwulan {
    tw1: ProgramStudi[]
    tw2?: ProgramStudi[]
    tw3?: ProgramStudi[]
}

const DATA: DataByTriwulan = {
    "tw1": [
        {
            "no": 1,
            "jenis": "Tinggi",
            "satdik": "Politeknik AUP",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": 271,
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": 260,
            "PTK": "",
            "TAK": 853,
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": 486,
            "TPI": 793,
            "TPPPI": "",
            "TPS": 191
        },
        {
            "no": 2,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Bitung",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": 133,
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": 213,
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": 147,
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 3,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Bone",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": 290,
            "TPPP": "",
            "TK": 188,
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": 181,
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 4,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Dumai",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": 85,
            "PP": "",
            "PTK": 81,
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 5,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Jembrana",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": 153,
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": 94,
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 6,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Karawang",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": 79,
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": 76,
            "TK": 61,
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": 63,
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 7,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Kupang",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": 114,
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": 250,
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": 160,
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 8,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Pangandaran",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": 100,
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": 68,
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 9,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Sidoarjo",
            "AGP": 117,
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": 77,
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": 179,
            "TPPP": 139,
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": 68,
            "TPS": ""
        },
        {
            "no": 10,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Sorong",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": 119,
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": 131,
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": 125,
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 11,
            "jenis": "Tinggi",
            "satdik": "Akademi Komunitas Wakatobi",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": 26,
            "Konservasi": 16,
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 12,
            "jenis": "Menengah",
            "satdik": "SUPM Kotaagung",
            "AGP": "",
            "APAPL": 26,
            "APHP": 18,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": 50,
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 13,
            "jenis": "Menengah",
            "satdik": "SUPM Ladong",
            "AGP": "",
            "APAPL": 37,
            "APHP": 24,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": 30,
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": 16,
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 14,
            "jenis": "Menengah",
            "satdik": "SUPM Pariaman",
            "AGP": "",
            "APAPL": 51,
            "APHP": 45,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": 54,
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": 30,
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 15,
            "jenis": "Menengah",
            "satdik": "SUPM Tegal",
            "AGP": "",
            "APAPL": 65,
            "APHP": 39,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": 75,
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": 38,
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 16,
            "jenis": "Menengah",
            "satdik": "SUPM Waeheru",
            "AGP": "",
            "APAPL": 52,
            "APHP": 46,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": 61,
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": 20,
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        }
    ],
    "tw2": [
        {
            "no": 1,
            "jenis": "Tinggi",
            "satdik": "Politeknik AUP",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": 271,
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": 191,
            "TK": "",
            "TK*": "",
            "TKPI": 845,
            "TPH": "",
            "TPI": 792,
            "TPPPI": 486,
            "TPS": ""
        },
        {
            "no": 2,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Bitung",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": 127,
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": 212,
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 3,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Bone",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": 290,
            "TAK": 188,
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 4,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Dumai",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": 111,
            "PHL": 80,
            "PMK": 85,
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 5,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Jembrana",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": 153,
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": 116,
            "PHL": 94,
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 6,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Karawang",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": 79,
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": 61,
            "TBP*": "",
            "TPPP": "",
            "TK": 76,
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 7,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Kupang",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": 114,
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": 250,
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 8,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Pangandaran",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": 101,
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": 100,
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": 67,
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 9,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Sidoarjo",
            "AGP": "",
            "APAPL": 117,
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": 77,
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": 179,
            "TAK": "",
            "TBP*": 69,
            "TPPP": "",
            "TK": 138,
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 10,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Sorong",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": 119,
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": 129,
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 11,
            "jenis": "Tinggi",
            "satdik": "Akademi Komunitas Wakatobi",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": 26,
            "Konservasi": 16,
            "KS": "",
            "MP": "",
            "MP*": "",
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 12,
            "jenis": "Menengah",
            "satdik": "SUPM Kotaagung",
            "AGP": "",
            "APAPL": "",
            "APHP": "",
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": 20,
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 13,
            "jenis": "Menengah",
            "satdik": "SUPM Ladong",
            "AGP": 6,
            "APAPL": "",
            "APHP": 10,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": 18,
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 14,
            "jenis": "Menengah",
            "satdik": "SUPM Pariaman",
            "AGP": 19,
            "APAPL": "",
            "APHP": 20,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": 20,
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 15,
            "jenis": "Menengah",
            "satdik": "SUPM Tegal",
            "AGP": "",
            "APAPL": "",
            "APHP": 37,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": 36,
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": "",
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        },
        {
            "no": 16,
            "jenis": "Menengah",
            "satdik": "SUPM Waeheru",
            "AGP": 19,
            "APAPL": "",
            "APHP": 16,
            "BDI": "",
            "EB": "",
            "Konservasi": "",
            "KS": "",
            "MP": "",
            "MP*": 19,
            "NKPI": "",
            "PHL": "",
            "PMK": "",
            "PP": "",
            "PTK": "",
            "TAK": "",
            "TBP*": "",
            "TPPP": "",
            "TK": "",
            "TK*": 20,
            "TKPI": "",
            "TPH": "",
            "TPI": "",
            "TPPPI": "",
            "TPS": ""
        }
    ],
    "tw3": [
        {
            "no": 1,
            "jenis": "Tinggi",
            "satdik": "Politeknik AUP",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": 245,
            "Permesinan Perikanan (MP)": 253,
            "Teknologi Akuakultur (TAK)": 776,
            "Teknologi Penangkapan Ikan (TPI)": 745,
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": 179,
            "Teknologi Pengolahan Hasil Perikanan (TPH)": 414
        },
        {
            "no": 2,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Bitung",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": 101,
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": 119,
            "Teknik Pengolahan Produk Perikanan (TPPP)": 173,
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 3,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Bone",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": 175,
            "Teknik Kelautan (TKL)": 124,
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": 128,
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 4,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Dumai",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": 98,
            "Perikanan Tangkap (PTK)": 75,
            "Permesinan Kapal (PMK)": 80,
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 5,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Jembrana",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": 114,
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": 81,
            "Perikanan Tangkap (PTK)": 79,
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 6,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Karawang",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": 82,
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": 65,
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": 74,
            "Teknik Pengolahan Produk Perikanan (TPPP)": 72,
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 7,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Kupang",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": 97,
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": 163,
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": 105,
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 8,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Pangandaran",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": 91,
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": 85,
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": 69,
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 9,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Sidoarjo",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": 111,
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": 83,
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": 210,
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": 79,
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": 165,
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 10,
            "jenis": "Tinggi",
            "satdik": "Politeknik KP Sorong",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": 96,
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": 103,
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": 104,
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 11,
            "jenis": "Tinggi",
            "satdik": "Akademi Komunitas Wakatobi",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": "",
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": "",
            "Nautika Kapal Penangkap Ikan (NKPI)": "",
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": 16,
            "Konservasi (KSV)": 16,
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 12,
            "jenis": "Menengah",
            "satdik": "SUPM Kotaagung",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": 19,
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": 20,
            "Nautika Kapal Penangkap Ikan (NKPI)": 38,
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 13,
            "jenis": "Menengah",
            "satdik": "SUPM Ladong",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": 26,
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": 30,
            "Nautika Kapal Penangkap Ikan (NKPI)": 38,
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 14,
            "jenis": "Menengah",
            "satdik": "SUPM Pariaman",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": 19,
            "Teknika Kapal Penangkap Ikan (TKPI)": 20,
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": 20,
            "Nautika Kapal Penangkap Ikan (NKPI)": 40,
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 15,
            "jenis": "Menengah",
            "satdik": "SUPM Tegal",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": 20,
            "Teknika Kapal Penangkap Ikan (TKPI)": "",
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": 57,
            "Nautika Kapal Penangkap Ikan (NKPI)": 56,
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        },
        {
            "no": 16,
            "jenis": "Menengah",
            "satdik": "SUPM Waeheru",
            "Agribisnis Pengolahan Hasil Perikanan (APHP)": 39,
            "Teknika Kapal Penangkap Ikan (TKPI)": 37,
            "Agribisnis Perikanan Air Payau dan Laut (APAPL)": 37,
            "Nautika Kapal Penangkap Ikan (NKPI)": 39,
            "Agribisnis Perikanan (AGP)": "",
            "Budidaya Ikan (BDI)": "",
            "Ekowisata Bahari (EWB)": "",
            "Konservasi (KSV)": "",
            "Mekanisasi Perikanan (MP)": "",
            "Mekanisasi Perikanan (MP*)": "",
            "Pengolahan Hasil Laut (PHL)": "",
            "Perikanan Tangkap (PTK)": "",
            "Permesinan Kapal (PMK)": "",
            "Teknik Budidaya Perikanan (TBP)": "",
            "Teknik Kelautan (TKL)": "",
            "Teknik Penanganan Patologi Perikanan (TPPI)": "",
            "Teknik Penangkapan Ikan (TPI)": "",
            "Teknik Pengolahan Produk Perikanan (TPPP)": "",
            "Teknologi Kelautan (TKL)": "",
            "Penyuluhan Perikanan (PP)": "",
            "Permesinan Perikanan (MP)": "",
            "Teknologi Akuakultur (TAK)": "",
            "Teknologi Penangkapan Ikan (TPI)": "",
            "Teknologi Pengelolaan Sumber Daya Perairan (TPS)": "",
            "Teknologi Pengolahan Hasil Perikanan (TPH)": ""
        }
    ]
}

const PRODI_KEYS = ['AGP', 'APAPL', 'APHP', 'BDI', 'EB', 'Konservasi', 'KS', 'MP', 'MP*', 'NKPI', 'PHL', 'PMK', 'PP', 'PTK', 'TAK', 'TBP*', 'TPPP', 'TK', 'TK*', 'TKPI', 'TPH', 'TPI', 'TPPPI', 'TPS']

const CardComponent = ({ title, children }: { title: string; children: React.ReactNode }) => (
    <div className="bg-navy-800 rounded-lg shadow-lg">
        <div className="px-6 py-4 border-b border-gray-700">
            <h3 className="text-lg font-semibold text-gray-100">{title}</h3>
        </div>
        {children}
    </div>
)

export default function TablePesertaDidikByProdi({
    loading = false,
    tahun = '2024',
    triwulan = 'tw1'
}: {
    loading?: boolean
    tahun?: string
    triwulan?: 'tw1' | 'tw2' | 'tw3'
}) {
    const [selectedJenis, setSelectedJenis] = useState<'Tinggi' | 'Menengah'>('Tinggi')

    const twLabel: Record<'tw1' | 'tw2' | 'tw3', string> = {
        tw1: 'TW I',
        tw2: 'TW II',
        tw3: 'TW III'
    }

    const calculateTotal = (item: ProgramStudi): number => {
        return PRODI_KEYS.reduce((sum, key) => {
            const value = item[key]
            return sum + (typeof value === 'number' ? value : 0)
        }, 0)
    }

    const { tinggi, menengah, chartData } = useMemo(() => {
        const currentData = DATA[triwulan] || DATA.tw1
        const tinggiData = currentData.filter(d => d.jenis === 'Tinggi')
        const menengahData = currentData.filter(d => d.jenis === 'Menengah')

        const tinggiTotal = tinggiData.reduce((sum, item) => sum + calculateTotal(item), 0)
        const menengahTotal = menengahData.reduce((sum, item) => sum + calculateTotal(item), 0)

        const chartData = [
            { name: 'Pendidikan Tinggi', Total: tinggiTotal },
            { name: 'Pendidikan Menengah', Total: menengahTotal }
        ]

        return { tinggi: tinggiData, menengah: menengahData, chartData }
    }, [triwulan])

    const renderTable = (data: ProgramStudi[], jenis: string) => {
        const activeProdi = PRODI_KEYS.filter(key => {
            return data.some(item => {
                const value = item[key]
                return typeof value === 'number' && (value as number) > 0
            })
        })
        return (
            <div className="overflow-x-auto rounded-lg p-5">
                <table className="w-full text-sm text-gray-200 border border-gray-700 bg-navy-700">
                    <thead className="bg-navy-800 text-gray-100 uppercase text-xs">
                        <tr>
                            <th className="px-4 py-2 border text-center sticky left-0 bg-navy-800 z-10">No</th>
                            <th className="px-4 py-2 border sticky left-12 bg-navy-800 z-10 min-w-[200px]">Satuan Pendidikan</th>
                            {activeProdi.map(prodi => (
                                <th key={prodi} className="px-4 py-2 border text-right whitespace-nowrap">{prodi}</th>
                            ))}
                            <th className="px-4 py-2 border text-right bg-navy-900 font-bold">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.map((item) => {
                            const total = calculateTotal(item)
                            return (
                                <tr key={item.no} className="border-t border-gray-700 hover:bg-navy-600">
                                    <td className="px-4 py-2 border text-center sticky left-0 bg-navy-700">{item.no}</td>
                                    <td className="px-4 py-2 border sticky left-12 bg-navy-700">{item.satdik}</td>
                                    {activeProdi.map(prodi => {
                                        const value = item[prodi]
                                        return (
                                            <td key={prodi} className="px-4 py-2 border text-right">
                                                {typeof value === 'number' && value > 0 ? value.toLocaleString('id-ID') : '-'}
                                            </td>
                                        )
                                    })}
                                    <td className="px-4 py-2 border text-right font-semibold bg-navy-800">
                                        {total.toLocaleString('id-ID')}
                                    </td>
                                </tr>
                            )
                        })}
                        <tr className="bg-navy-800 font-bold">
                            <td colSpan={2} className="px-4 py-2 border text-right sticky left-0 bg-navy-800 z-10">
                                Total {jenis}
                            </td>
                            {activeProdi.map(prodi => {
                                const total = data.reduce((sum, item) => {
                                    const value = item[prodi]
                                    return sum + (typeof value === 'number' ? value : 0)
                                }, 0)
                                return (
                                    <td key={prodi} className="px-4 py-2 border text-right">
                                        {total > 0 ? total.toLocaleString('id-ID') : '-'}
                                    </td>
                                )
                            })}
                            <td className="px-4 py-2 border text-right bg-navy-900">
                                {data.reduce((sum, item) => sum + calculateTotal(item), 0).toLocaleString('id-ID')}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        )
    }

    if (loading) {
        return (
            <div className="flex h-[25vh] py-10 items-center justify-center">
                <div className="text-gray-300">Loading...</div>
            </div>
        )
    }

    return (
        <div className="space-y-6 p-6 bg-navy-900 min-h-screen">
            <CardComponent title={`Data Peserta Didik Berdasarkan Program Studi ${tahun} - ${twLabel[triwulan]}`}>
                <div className="p-5">
                    <ResponsiveContainer width="100%" height={300}>
                        <BarChart data={chartData}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
                            <XAxis dataKey="name" stroke="#9CA3AF" />
                            <YAxis stroke="#9CA3AF" />
                            <Tooltip
                                contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #374151', color: '#fff' }}
                                formatter={(value: number) => value.toLocaleString('id-ID')}
                            />
                            <Legend />
                            <Bar dataKey="Total" fill="#3b82f6" />
                        </BarChart>
                    </ResponsiveContainer>
                </div>
            </CardComponent>

            <div className="bg-navy-800 rounded-lg shadow-lg">
                <div className="px-6 py-4 border-b border-gray-700 flex items-center justify-between">
                    <h3 className="text-lg font-semibold text-gray-100">Berdasarkan Program Studi</h3>
                    <select
                        value={selectedJenis}
                        onChange={(e) => setSelectedJenis(e.target.value as 'Tinggi' | 'Menengah')}
                        className="px-4 py-2 bg-navy-700 text-gray-100 border border-gray-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 cursor-pointer"
                    >
                        <option value="Tinggi">Pendidikan Tinggi</option>
                        <option value="Menengah">Pendidikan Menengah</option>
                    </select>
                </div>
                {selectedJenis === 'Tinggi'
                    ? renderTable(tinggi, 'Pendidikan Tinggi')
                    : renderTable(menengah, 'Pendidikan Menengah')
                }
            </div>
        </div>
    )
}